/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.autosite.struts.act;

import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;
import org.apache.log4j.Logger;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.autosite.db.Site;
import com.autosite.ds.SiteDS;
import com.autosite.struts.action.core.AutositeCoreAction;
import com.autosite.util.DefaultActionMapper;

/** 
 * 
 */
public class DynamicMenuAction4 extends AutositeCoreAction {
    /*
     * Generated Methods
     */
    protected DefaultActionMapper m_actionMapper;

    public DynamicMenuAction4(){
        m_actionMapper = DefaultActionMapper.getInstance();
    }
    /** 
     * Method execute
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward ex(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) {
        HttpSession session = request.getSession();
        
        Site site = SiteDS.getInstance().registerSite(request.getServerName());
        String url = request.getRequestURI();
        m_logger.debug(url);
        
        String parts[] = url.split("/");

        m_logger.debug("num parts=" + parts.length);
        
        if ( parts.length < 1 ) {
            m_logger.info("length of parts is too short. returning as error");
            sessionErrorText(session, "Invalid request");
            return mapping.findForward("default");
        }

        AutositeCoreAction action = findAction(url);
        if (action != null) 
            return action.ex(mapping, form, request, response);
        
        setPage(session, "error_not_found");
        return mapping.findForward("default");
    }
    
    public Map exAjax(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) {
        String url = request.getRequestURI();
        AutositeCoreAction action = findAction(url);
        if (action != null) 
            return action.exAjax(mapping, form, request, response);
        
        Map ret  = new HashMap();
        ret.put("__error", "true");
        return ret;
        
    }    
    
    protected boolean isActionCmd(HttpServletRequest request){
        return super.isActionBasicCmd(request); 
    }    
    
    protected boolean loginRequired() {
        return false;
    }
    
    protected AutositeCoreAction findAction(String url){
        
        String parts[] = url.split("/");

        m_logger.debug("num parts=" + parts.length);
        
        if ( parts.length < 1 ) {
            return null;
        }

        String actionRoute = parts[1].substring(0, parts[1].length()-5);
        
        if ( m_actionMapper.getCoreAction(actionRoute) == null){

            String actionClass = null;

            if (actionRoute.endsWith("AjaxAction")){
                actionClass = "com.autosite.struts.action." + StringUtils.capitalize(actionRoute);
            } else if  (actionRoute.endsWith("Action")){
                actionClass = "com.autosite.struts.action." + StringUtils.capitalize(actionRoute.replaceAll("Action", "AjaxAction"));
            }
            
            m_logger.info("Action class to run " + actionClass);
            
            try {
                AutositeCoreAction action = (AutositeCoreAction)Class.forName(actionClass).newInstance();
                m_actionMapper.register(actionRoute, action);
                m_logger.info("New Action registered " + actionRoute + " class " + actionClass);
            }
            catch (Exception e) {
                m_logger.error(e.getMessage(), e);
            }
        } 
        return m_actionMapper.getCoreAction(actionRoute);
    }
    
    private static Logger m_logger = Logger.getLogger(DynamicMenuAction4.class);
}
