/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.autosite.struts.act;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.log4j.Logger;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.autosite.app.AutositeLoginExtentExecutor;
import com.autosite.db.AutositeLoginExtent;
import com.autosite.db.AutositeUser;
import com.autosite.db.Site;
import com.autosite.ds.AutositeLoginExtentDS;
import com.autosite.ds.SiteDS;
import com.autosite.struts.action.core.AutositeCoreAction;
import com.autosite.util.UserUtil;
import com.jtrend.session.PageView;
import com.jtrend.struts.core.DefaultViewManager;

/**
 * MyEclipse Struts Creation date: 07-14-2007
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/loginFormSubmit" name="loginForm"
 *                input="/jsp/form/login.jsp" scope="request" validate="true"
 * @struts.action-forward name="default" path="/jsp/layout/layout.jsp"
 * 
 * 
 * This is sample how to use moveTO
 * 
 * <a href="/moveTo.html?dest=<%=cancelPage%>">Cancel</a>
 * <a href="/moveTo.html?dest=http://www.yahoo.com">Yahoo</a>
 */
public class MoveToAction extends AutositeCoreAction {
    /*
     * Generated Methods
     */

    /**
     * Method execute
     * 
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward ex(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) {

        HttpSession session = request.getSession();

        Site site = SiteDS.getInstance().registerSite(request.getServerName());
        if (site == null) {
            sessionErrorText(session, "Internal error occurred. Please try once again");
            return mapping.findForward("default");
        }
        
        String dest = request.getParameter("dest");
        
        if ( dest != null){
            m_logger.debug("MoveTo dest=" + dest );

            if (dest.startsWith("http://")){

                ActionForward actionForward = new ActionForward(request.getParameter("dest"), true);
                return actionForward;
            } 
            String returnPage = dest;
            int pos = returnPage.indexOf(",");

            String pagePart = "";
            String parmPart = "";
            
            if (pos > 0){
                pagePart = returnPage.substring(0, pos);
                parmPart = returnPage.substring(pos+1);
                
                returnPage = pagePart;
                m_logger.debug("returnPage embedded params. Copying to reserved Params=" +parmPart );
                copyToPreserveParams(parmPart, session);
            } else {

            }
            
            PageView viewPage = m_viewManager.getPageView(returnPage, getServerForPage(session));
            
            if ( viewPage != null ) {
                setPage(request, returnPage);
            } else {
                setPage(request, "error_not_found");
            }
        } 
        
        return mapping.findForward("default");
    }

    protected boolean staticAuthenticate(String username, String password) {

        if (username != null && username.trim().equals("autosite") && password != null && password.trim().equals("autosite"))
            return true;
        
        
        
        return false;
    }

    protected AutositeUser dbAuthenticate(Site site, String username, String password) {
        AutositeUser user = UserUtil.findUser(site, username);

        if ( user == null ) {
            m_logger.info("User object not found for " + username);
            return null;
        }
        
        if (password != null && password.equals(user.getPassword())) {
            return user;
        }
        else {
            return null;
        }
    }

    protected boolean executeExtent (HttpServletRequest request, AutositeUser user) throws Exception{
        
        
        Site site = SiteDS.getInstance().registerSite(request.getServerName());
        
        AutositeLoginExtent extent = AutositeLoginExtentDS.getInstance().getObjectBySiteId(site.getId());
        
        if (extent != null){
            
            try {
                AutositeLoginExtentExecutor executor = (AutositeLoginExtentExecutor)Class.forName(extent.getClassName()).newInstance();
                executor.execute(request, user);
            }
            catch (Exception e) {
                m_logger.error(e.getMessage(),e);
            }
        }
        
        return true;
    }
    
    
    
    
    protected boolean loginRequired() {
        return false;
    }

    private static Logger m_logger = Logger.getLogger(MoveToAction.class);
}
