/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.surveygen.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.jtrend.struts.core.JtrendAction;

/** 
 * MyEclipse Struts
 * Creation date: 07-08-2007
 * 
 * XDoclet definition:
 * @struts.action scope="request" validate="true"
 */
abstract public class SurveyGenCoreAction extends JtrendAction {
    
    public SurveyGenCoreAction() {
        super();
    }

//    public ActionForward ex(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) {
//        return ex(mapping, form, request, response);
//    }

    private static Logger m_logger = Logger.getLogger(SurveyGenCoreAction.class);
}