/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.autosite.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.log4j.Logger;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.autosite.content.ContentSilo;
import com.autosite.struts.action.core.AutositeCoreAction;
import com.autosite.struts.form.AddContentForm;

/** 
 * MyEclipse Struts
 * Creation date: 02-02-2008
 * 
 * XDoclet definition:
 * @struts.action path="/addContent" name="addContentForm" input="/form/addContent.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/jsp/layout/layout.jsp" contextRelative="true"
 */
public class AddContentAction extends AutositeCoreAction {
    /*
     * Generated Methods
     */

    /** 
     * Method execute
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward ex(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) {
        AddContentForm addContentForm = (AddContentForm) form;// TODO Auto-generated method stub
        HttpSession session = request.getSession();
        
        m_logger.debug(addContentForm.getContent());

        boolean html = false;
        if (!isMissing(request.getParameter("html"))) {
            html = true;
        }
        
        String content = addContentForm.getContent();
        if (!html) {
            content = content.replace("\n", "<BR>");
        }
        ContentSilo.getInstance().store(request.getServerName(), content);
        setPage(session, request.getServerName(), "home");
        return mapping.findForward("default");
    }
    protected boolean loginRequired() {
        return true;
    }

    private static Logger m_logger = Logger.getLogger(AddContentAction.class);
}
