/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.autosite.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.autosite.struts.action.core.AutositeCoreAction;
import com.surveygen.struts.action.SurveyGenCoreAction;

/** 
 * MyEclipse Struts
 * Creation date: 07-16-2007
 * 
 * XDoclet definition:
 * @struts.action scope="request" validate="true"
 * @struts.action-forward name="default" path="/jsp/layout/layout.jsp" contextRelative="true"
 */
public class AutositeLogoutAction extends AutositeCoreAction {
    /*
     * Generated Methods
     */

    /** 
     * Method execute
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward ex(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) {
        HttpSession session = request.getSession();
        
        setLogout(session);

        setPage(session, request.getServerName(), "home");
        return mapping.findForward("default");
    }
    
    protected boolean loginRequired() {
        return false;
    }

}
