/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.autosite.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.autosite.content.ContentSilo;
import com.autosite.struts.action.core.AutositeCoreAction;

/** 
 * MyEclipse Struts
 * Creation date: 02-08-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="defaults" path="/jsp/layout/layout.jsp" contextRelative="true"
 */
public class DeleteContentAction extends AutositeCoreAction {
    /*
     * Generated Methods
     */

    /** 
     * Method execute
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward ex(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) {
        // TODO Auto-generated method stub
        HttpSession session = request.getSession();
        
        String contentId = request.getParameter("id");

        ContentSilo.getInstance().delete(contentId);
        
        setPage(session, request.getServerName(),  "home");
        return mapping.findForward("default");
    }

    @Override
    protected boolean loginRequired() {
        // TODO Auto-generated method stub
        return true;
    }
    
    
}
