/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.autosite.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.log4j.Logger;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.autosite.db.Site;
import com.autosite.db.SitePost;
import com.autosite.ds.SiteDS;
import com.autosite.ds.SitePostDS;
import com.autosite.struts.action.core.AutositeCoreAction;

/** 
 * MyEclipse Struts
 * Creation date: 05-31-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="default" path="/jsp/layout/layout.jsp" contextRelative="true"
 */
public class DeleteSitePostAction extends AutositeCoreAction {
    /*
     * Generated Methods
     */

    /** 
     * Method execute
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward ex(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) {
        HttpSession session = request.getSession();


        if (isMissing(request.getParameter("id"))) {
            sessionErrorText(session, "Invalid request");
            setPage(session, request.getServerName(), "home");
            return mapping.findForward("default");
        }

        long postId = -1;
        try {
            postId = Long.parseLong(request.getParameter("id"));
        }
        catch (NumberFormatException e) {
            
        }
        
        SitePost sitePost = SitePostDS.getInstance().getById(new Long(postId));
        
        if (sitePost == null) {
            sessionErrorText(session, "Invalid request");
            setPage(session, request.getServerName(), "home");
            return mapping.findForward("default");
        }
        
        Site site = SiteDS.getInstance().registerSite(request.getServerName());

        if ( site !=null && sitePost.getPostScope() != 1 && ( site.getId() != sitePost.getSiteId())) {
            sessionErrorText(session, "Invalid request");
            setPage(session, request.getServerName(), "home");
            return mapping.findForward("default");
        }
        
        SitePostDS.getInstance().delete(sitePost);

        sessionTopText(session, "Deleted");
        m_logger.info("Site post has been deleted " + sitePost.getId() + " from site " + site.getSiteUrl());
        
        setPage(session, request.getServerName(), "home");
        return mapping.findForward("default");
    }
    
    protected boolean loginRequired() {
        return true;
    }
    
    private static Logger m_logger = Logger.getLogger(DeleteSitePostAction.class);
}
