package com.surveygen.db;

/**
 * Check2table generated by MyEclipse Persistence Tools
 */

public class Check2table implements java.io.Serializable {

	// Fields

	private Long check2Id;

	private String check2Val;

	// Constructors

	/** default constructor */
	public Check2table() {
	}

	/** full constructor */
	public Check2table(String check2Val) {
		this.check2Val = check2Val;
	}

	// Property accessors

	public Long getCheck2Id() {
		return this.check2Id;
	}

	public void setCheck2Id(Long check2Id) {
		this.check2Id = check2Id;
	}

	public String getCheck2Val() {
		return this.check2Val;
	}

	public void setCheck2Val(String check2Val) {
		this.check2Val = check2Val;
	}

}