package com.surveygen.db;

/**
 * CheckTable generated by MyEclipse Persistence Tools
 */

public class CheckTable implements java.io.Serializable {

	// Fields

	private long checkId;

	private int checVal;

	private long checkLong;

	private boolean checkBool;

	// Constructors

	/** default constructor */
	public CheckTable() {
	}

	/** full constructor */
	public CheckTable(int checVal, long checkLong, boolean checkBool) {
		this.checVal = checVal;
		this.checkLong = checkLong;
		this.checkBool = checkBool;
	}

	// Property accessors

	public long getCheckId() {
		return this.checkId;
	}

	public void setCheckId(long checkId) {
		this.checkId = checkId;
	}

	public int getChecVal() {
		return this.checVal;
	}

	public void setChecVal(int checVal) {
		this.checVal = checVal;
	}

	public long getCheckLong() {
		return this.checkLong;
	}

	public void setCheckLong(long checkLong) {
		this.checkLong = checkLong;
	}

	public boolean getCheckBool() {
		return this.checkBool;
	}

	public void setCheckBool(boolean checkBool) {
		this.checkBool = checkBool;
	}

}