package com.surveygen.db;

import java.util.Date;

/**
 * User generated by MyEclipse Persistence Tools
 */

public class User implements java.io.Serializable {

    // Fields

    private long userId;
    private String username;
    private String password;
    private String email;
    private Date createdT;
    private Date activatedT;

    // Constructors

    /** default constructor */
    public User() {
    }

    /** minimal constructor */
    public User(String username, String password, String email, Date createdT) {
        this.username = username;
        this.password = password;
        this.email = email;
        this.createdT = createdT;
    }

    /** full constructor */
    public User(String username, String password, String email, Date createdT, Date activatedT) {
        this.username = username;
        this.password = password;
        this.email = email;
        this.createdT = createdT;
        this.activatedT = activatedT;
    }

    // Property accessors

    public long getUserId() {
        return this.userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Date getCreatedT() {
        return this.createdT;
    }

    public void setCreatedT(Date createdT) {
        this.createdT = createdT;
    }

    public Date getActivatedT() {
        return this.activatedT;
    }

    public void setActivatedT(Date activatedT) {
        this.activatedT = activatedT;
    }

}
