/* 
Template last modification history:


Source Generated: Sat Feb 14 00:12:25 EST 2015
*/

package com.autosite.db;

import com.surveygen.db.BaseHibernateDAO;
import java.sql.Timestamp;
import java.util.List;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.hibernate.LockMode;
import org.hibernate.Query;
import org.hibernate.criterion.Example;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/* DAO is generated by Eclipse. This is by AutoGen
 *
 */
public class SynkNodeTrackerTxDAO2  extends BaseHibernateDAO  {
    private static Logger log = LoggerFactory.getLogger(SynkNodeTrackerTxDAO2.class);

	public static final String ID = "id";
	public static final String SITE_ID = "siteId";
	public static final String NAMESPACE = "namespace";
	public static final String DEVICE_ID = "deviceId";
	public static final String TX_TOKEN = "txToken";
	public static final String STAMP_ACKED = "stampAcked";
	public static final String STAMP_LAST = "stampLast";
	public static final String NUM_RECORDS = "numRecords";
	public static final String IP = "ip";
	public static final String TIME_CREATED = "timeCreated";

    public void save(SynkNodeTrackerTx transientInstance) {
        log.debug("saving SynkNodeTrackerTx instance");
        try {
            getSession().save(transientInstance);
            log.debug("save successful");
        }
        catch (RuntimeException re) {
            log.error("save failed", re);
            throw re;
        }
    }

    public void delete(SynkNodeTrackerTx persistentInstance) {
        log.debug("deleting SynkNodeTrackerTx instance");
        try {
            getSession().delete(persistentInstance);
            log.debug("delete successful");
        }
        catch (RuntimeException re) {
            log.error("delete failed", re);
            throw re;
        }
    }

    public SynkNodeTrackerTx findById(Long id) {
        log.debug("getting SynkNodeTrackerTx instance with id: " + id);
        try {
            SynkNodeTrackerTx instance = (SynkNodeTrackerTx) getSession().get("com.autosite.db.SynkNodeTrackerTx", id);
            return instance;
        }
        catch (RuntimeException re) {
            log.error("get failed", re);
            throw re;
        }
    }

    public List findByExample(SynkNodeTrackerTx instance) {
        log.debug("finding SynkNodeTrackerTx instance by example");
        try {
            List results = getSession().createCriteria("com.autosite.db.SynkNodeTrackerTx").add(Example.create(instance)).list();
            log.debug("find by example successful, result size: " + results.size());
            return results;
        }
        catch (RuntimeException re) {
            log.error("find by example failed", re);
            throw re;
        }
    }

    public List findByProperty(String propertyName, Object value) {
        log.debug("finding SynkNodeTrackerTx instance with property: " + propertyName + ", value: " + value);
        try {
            String queryString = "from SynkNodeTrackerTx as model where model." + propertyName + "= ?";
            Query queryObject = getSession().createQuery(queryString);
            queryObject.setParameter(0, value);
            return queryObject.list();
        }
        catch (RuntimeException re) {
            log.error("find by property name failed", re);
            throw re;
        }
    }

    public List findById(Object id) {
        return findByProperty(ID, id);
    }
    public List findBySiteId(Object siteId) {
        return findByProperty(SITE_ID, siteId);
    }
    public List findByNamespace(Object namespace) {
        return findByProperty(NAMESPACE, namespace);
    }
    public List findByDeviceId(Object deviceId) {
        return findByProperty(DEVICE_ID, deviceId);
    }
    public List findByTxToken(Object txToken) {
        return findByProperty(TX_TOKEN, txToken);
    }
    public List findByStampAcked(Object stampAcked) {
        return findByProperty(STAMP_ACKED, stampAcked);
    }
    public List findByStampLast(Object stampLast) {
        return findByProperty(STAMP_LAST, stampLast);
    }
    public List findByNumRecords(Object numRecords) {
        return findByProperty(NUM_RECORDS, numRecords);
    }
    public List findByIp(Object ip) {
        return findByProperty(IP, ip);
    }
    public List findByTimeCreated(Object timeCreated) {
        return findByProperty(TIME_CREATED, timeCreated);
    }

    public List findAll() {
        log.debug("finding all SynkNodeTrackerTx instances");
        try {
            String queryString = "from SynkNodeTrackerTx";
            Query queryObject = getSession().createQuery(queryString);
            return queryObject.list();
        }
        catch (RuntimeException re) {
            log.error("find all failed", re);
            throw re;
        }
    }

    public SynkNodeTrackerTx merge(SynkNodeTrackerTx detachedInstance) {
        log.debug("merging SynkNodeTrackerTx instance");
        try {
            SynkNodeTrackerTx result = (SynkNodeTrackerTx) getSession().merge(detachedInstance);
            log.debug("merge successful");
            return result;
        }
        catch (RuntimeException re) {
            log.error("merge failed", re);
            throw re;
        }
    }

    public void attachDirty(SynkNodeTrackerTx instance) {
        log.debug("attaching dirty SynkNodeTrackerTx instance");
        try {
            getSession().saveOrUpdate(instance);
            log.debug("attach successful");
        }
        catch (RuntimeException re) {
            log.error("attach failed", re);
            throw re;
        }
    }

    public void attachClean(SynkNodeTrackerTx instance) {
        log.debug("attaching clean SynkNodeTrackerTx instance");
        try {
            getSession().lock(instance, LockMode.NONE);
            log.debug("attach successful");
        }
        catch (RuntimeException re) {
            log.error("attach failed", re);
            throw re;
        }
    }



}