package com.seox.db;

import java.util.Date;


/**
 * Category generated by MyEclipse - Hibernate Tools
 */

public class Category  implements java.io.Serializable {


    // Fields    

     private long categoryId;
     private String categoryName;
     private long userId;
     private Date enteredT;


    // Constructors

    /** default constructor */
    public Category() {
    }

    
    /** full constructor */
    public Category(long categoryId, String categoryName, long userId, Date enteredT) {
        this.categoryId = categoryId;
        this.categoryName = categoryName;
        this.userId = userId;
        this.enteredT = enteredT;
    }

   
    // Property accessors

    public long getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(long categoryId) {
        this.categoryId = categoryId;
    }

    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }

    public Date getEnteredT() {
        return this.enteredT;
    }
    
    public void setEnteredT(Date enteredT) {
        this.enteredT = enteredT;
    }
   








}