package com.seox.db;



/**
 * Innotest generated by MyEclipse - Hibernate Tools
 */

public class Innotest  implements java.io.Serializable {


    // Fields    

     private long id;
     private String value;


    // Constructors

    /** default constructor */
    public Innotest() {
    }

    
    /** full constructor */
    public Innotest(String value) {
        this.value = value;
    }

   
    // Property accessors

    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
   








}