package com.seox.db;

import java.util.Date;


/**
 * Note generated by MyEclipse - Hibernate Tools
 */

public class Note  implements java.io.Serializable {


    // Fields    

     private long noteId;
     private String noteStr;
     private Date noteEnteredT;
     private long userId;


    // Constructors

    /** default constructor */
    public Note() {
    }

    
    /** full constructor */
    public Note(String noteStr, Date noteEnteredT, long userId) {
        this.noteStr = noteStr;
        this.noteEnteredT = noteEnteredT;
        this.userId = userId;
    }

   
    // Property accessors

    public long getNoteId() {
        return this.noteId;
    }
    
    public void setNoteId(long noteId) {
        this.noteId = noteId;
    }

    public String getNoteStr() {
        return this.noteStr;
    }
    
    public void setNoteStr(String noteStr) {
        this.noteStr = noteStr;
    }

    public Date getNoteEnteredT() {
        return this.noteEnteredT;
    }
    
    public void setNoteEnteredT(Date noteEnteredT) {
        this.noteEnteredT = noteEnteredT;
    }

    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
   








}