package com.seox.db;



/**
 * Rank generated by MyEclipse - Hibernate Tools
 */

public class Rank  implements java.io.Serializable {


    // Fields    

     private long rankId;
     private Keyword keyword;
     private String domain;
     private String link;
     private int weekNum;
     private int dayNum;
     private int rank;
     private int searchEngine;


    // Constructors

    /** default constructor */
    public Rank() {
    }

	/** minimal constructor */
    public Rank(long rankId, Keyword keyword, String domain, String link, int rank, int searchEngine) {
        this.rankId = rankId;
        this.keyword = keyword;
        this.domain = domain;
        this.link = link;
        this.rank = rank;
        this.searchEngine = searchEngine;
    }
    
    /** full constructor */
    public Rank(long rankId, Keyword keyword, String domain, String link, int weekNum, int dayNum, int rank, int searchEngine) {
        this.rankId = rankId;
        this.keyword = keyword;
        this.domain = domain;
        this.link = link;
        this.weekNum = weekNum;
        this.dayNum = dayNum;
        this.rank = rank;
        this.searchEngine = searchEngine;
    }

   
    // Property accessors

    public long getRankId() {
        return this.rankId;
    }
    
    public void setRankId(long rankId) {
        this.rankId = rankId;
    }

    public Keyword getKeyword() {
        return this.keyword;
    }
    
    public void setKeyword(Keyword keyword) {
        this.keyword = keyword;
    }

    public String getDomain() {
        return this.domain;
    }
    
    public void setDomain(String domain) {
        this.domain = domain;
    }

    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }

    public int getWeekNum() {
        return this.weekNum;
    }
    
    public void setWeekNum(int weekNum) {
        this.weekNum = weekNum;
    }

    public int getDayNum() {
        return this.dayNum;
    }
    
    public void setDayNum(int dayNum) {
        this.dayNum = dayNum;
    }

    public int getRank() {
        return this.rank;
    }
    
    public void setRank(int rank) {
        this.rank = rank;
    }

    public int getSearchEngine() {
        return this.searchEngine;
    }
    
    public void setSearchEngine(int searchEngine) {
        this.searchEngine = searchEngine;
    }
   








}