package com.seox.db;

import java.util.Date;


/**
 * UserDomain generated by MyEclipse - Hibernate Tools
 */

public class UserDomain  implements java.io.Serializable {


    // Fields    

     private long userDomainId;
     private User user;
     private String domain;
     private Date enteredT;
     private byte active;
     private long categoryId;


    // Constructors

    /** default constructor */
    public UserDomain() {
    }

    
    /** full constructor */
    public UserDomain(long userDomainId, User user, String domain, Date enteredT, byte active, long categoryId) {
        this.userDomainId = userDomainId;
        this.user = user;
        this.domain = domain;
        this.enteredT = enteredT;
        this.active = active;
        this.categoryId = categoryId;
    }

   
    // Property accessors

    public long getUserDomainId() {
        return this.userDomainId;
    }
    
    public void setUserDomainId(long userDomainId) {
        this.userDomainId = userDomainId;
    }

    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    public String getDomain() {
        return this.domain;
    }
    
    public void setDomain(String domain) {
        this.domain = domain;
    }

    public Date getEnteredT() {
        return this.enteredT;
    }
    
    public void setEnteredT(Date enteredT) {
        this.enteredT = enteredT;
    }

    public byte getActive() {
        return this.active;
    }
    
    public void setActive(byte active) {
        this.active = active;
    }

    public long getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(long categoryId) {
        this.categoryId = categoryId;
    }
   








}