package com.seox.db;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * User generated by MyEclipse - Hibernate Tools
 */

public class User  implements java.io.Serializable {


    // Fields    

     private long userId;
     private String username;
     private String password;
     private String firstname;
     private String lastname;
     private String email;
     private Date registeredT;
     private Date activatedT;
     private String googleKey;
     private int type;
     private Set userKeywordMaps = new HashSet(0);
     private Set userDomains = new HashSet(0);


    // Constructors

    /** default constructor */
    public User() {
    }

	/** minimal constructor */
    public User(String username, String password, String firstname, String lastname, String email, int type) {
        this.username = username;
        this.password = password;
        this.firstname = firstname;
        this.lastname = lastname;
        this.email = email;
        this.type = type;
    }
    
    /** full constructor */
    public User(String username, String password, String firstname, String lastname, String email, Date registeredT, Date activatedT, String googleKey, int type, Set userKeywordMaps, Set userDomains) {
        this.username = username;
        this.password = password;
        this.firstname = firstname;
        this.lastname = lastname;
        this.email = email;
        this.registeredT = registeredT;
        this.activatedT = activatedT;
        this.googleKey = googleKey;
        this.type = type;
        this.userKeywordMaps = userKeywordMaps;
        this.userDomains = userDomains;
    }

   
    // Property accessors

    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }

    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public Date getRegisteredT() {
        return this.registeredT;
    }
    
    public void setRegisteredT(Date registeredT) {
        this.registeredT = registeredT;
    }

    public Date getActivatedT() {
        return this.activatedT;
    }
    
    public void setActivatedT(Date activatedT) {
        this.activatedT = activatedT;
    }

    public String getGoogleKey() {
        return this.googleKey;
    }
    
    public void setGoogleKey(String googleKey) {
        this.googleKey = googleKey;
    }

    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
   
    public Set getUserKeywordMaps() {
        return this.userKeywordMaps;
    }
    
    public void setUserKeywordMaps(Set userKeywordMaps) {
        this.userKeywordMaps = userKeywordMaps;
    }

    public Set getUserDomains() {
        return this.userDomains;
    }
    
    public void setUserDomains(Set userDomains) {
        this.userDomains = userDomains;
    }







}