package com.seox.db;

import java.util.Date;


/**
 * UserKeywordMap generated by MyEclipse - Hibernate Tools
 */

public class UserKeywordMap  implements java.io.Serializable {


    // Fields    

     private long userKeywordMapId;
     private User user;
     private long keywordId;
     private Date enteredT;
     private byte active;
     private long categoryId;


    // Constructors

    /** default constructor */
    public UserKeywordMap() {
    }

    
    /** full constructor */
    public UserKeywordMap(long userKeywordMapId, User user, long keywordId, Date enteredT, byte active, long categoryId) {
        this.userKeywordMapId = userKeywordMapId;
        this.user = user;
        this.keywordId = keywordId;
        this.enteredT = enteredT;
        this.active = active;
        this.categoryId = categoryId;
    }

   
    // Property accessors

    public long getUserKeywordMapId() {
        return this.userKeywordMapId;
    }
    
    public void setUserKeywordMapId(long userKeywordMapId) {
        this.userKeywordMapId = userKeywordMapId;
    }

    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    public long getKeywordId() {
        return this.keywordId;
    }
    
    public void setKeywordId(long keywordId) {
        this.keywordId = keywordId;
    }

    public Date getEnteredT() {
        return this.enteredT;
    }
    
    public void setEnteredT(Date enteredT) {
        this.enteredT = enteredT;
    }

    public byte getActive() {
        return this.active;
    }
    
    public void setActive(byte active) {
        this.active = active;
    }

    public long getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(long categoryId) {
        this.categoryId = categoryId;
    }
   








}