/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.autosite.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-02-2008
 * 
 * XDoclet definition:
 * @struts.form name="addContentForm"
 */
public class AddContentForm extends ActionForm {
    /*
     * Generated fields
     */

    /** content property */
    private String content;

    /*
     * Generated Methods
     */

    /** 
     * Method validate
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {
        // TODO Auto-generated method stub
        return null;
    }

    /** 
     * Method reset
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // TODO Auto-generated method stub
    }

    /** 
     * Returns the content.
     * @return String
     */
    public String getContent() {
        return content;
    }

    /** 
     * Set the content.
     * @param content The content to set
     */
    public void setContent(String content) {
        this.content = content;
    }
}
