/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.autosite.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-21-2008
 * 
 * XDoclet definition:
 * @struts.form name="addPageForm"
 */
public class AddPageForm extends ActionForm {
    /*
     * Generated fields
     */

    /** page property */
    private String page;
    private String pageDisplay;
    private String headerPage;
    private String menuPanelId;
    private String parentPageId;
    private String alt1;
    private String alt2;
    private String alt3;
    private String underlyingPage;
    
    
    /*
     * Generated Methods
     */

    public String getUnderlyingPage() {
        return underlyingPage;
    }

    public void setUnderlyingPage(String underlyingPage) {
        this.underlyingPage = underlyingPage;
    }

    public String getParentPageId() {
        return parentPageId;
    }

    public String getAlt1() {
        return alt1;
    }

    public void setAlt1(String alt1) {
        this.alt1 = alt1;
    }

    public String getAlt2() {
        return alt2;
    }

    public void setAlt2(String alt2) {
        this.alt2 = alt2;
    }

    public String getAlt3() {
        return alt3;
    }

    public void setAlt3(String alt3) {
        this.alt3 = alt3;
    }

    public void setParentPageId(String parentPageId) {
        this.parentPageId = parentPageId;
    }

    public String getMenuPanelId() {
        return menuPanelId;
    }

    public void setMenuPanelId(String menuPanelId) {
        this.menuPanelId = menuPanelId;
    }

    public String getPageDisplay() {
        return pageDisplay;
    }

    public void setPageDisplay(String pageDisplay) {
        this.pageDisplay = pageDisplay;
    }

    /** 
     * Method validate
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {
        // TODO Auto-generated method stub
        return null;
    }

    /** 
     * Method reset
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // TODO Auto-generated method stub
    }

    /** 
     * Returns the page.
     * @return String
     */
    public String getPage() {
        return page;
    }

    /** 
     * Set the page.
     * @param page The page to set
     */
    public void setPage(String page) {
        this.page = page;
    }

    public String getHeaderPage() {
        return headerPage;
    }

    public void setHeaderPage(String headerPage) {
        this.headerPage = headerPage;
    }
    
}
