/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.autosite.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 07-21-2008
 * 
 * XDoclet definition:
 * @struts.form name="fileupForm"
 */
public class FileupForm extends ActionForm {
    /*
     * Generated fields
     */

    /** formFile property */
    private FormFile formFile;
    private String fileType;
    
    /*
     * Generated Methods
     */

    /** 
     * Method validate
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {
        // TODO Auto-generated method stub
        return null;
    }

    /** 
     * Method reset
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // TODO Auto-generated method stub
    }

    /** 
     * Returns the formFile.
     * @return FormFile
     */
    public FormFile getFormFile() {
        return formFile;
    }

    /** 
     * Set the formFile.
     * @param formFile The formFile to set
     */
    public void setFormFile(FormFile formFile) {
        this.formFile = formFile;
    }

    public String getFileType() {
        return fileType;
    }

    public void setFileType(String fileType) {
        this.fileType = fileType;
    }
    
    
}
