/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.autosite.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-29-2008
 * 
 * XDoclet definition:
 * @struts.form name="siteConfigForm"
 */
public class SiteConfigForm extends ActionForm {
    /*
     * Generated fields
     */

    /** width property */
    private String width;

    /** track_google property */
    private String track_google;

    /** keywords property */
    private String keywords;

    /** meta property */
    private String meta;

    private String header;
    private String colCount;
    private String clrSubmenuBg;
    private String clrBorders;
    private String contactInfo;
    private String siteGroup;
    private String headerImage;
    private String headerImageHeight;
    private String headerImageWidth;
    private String headerAd;
    
    private String menuWidth;
    private String adWidth; 

    private String menuFrontColor;
    private String menuBackColor;
    private String menuLineColor;
    private String menuReverse;
    private String displayAllHome;
    private String layoutPage;
    private String underlyingHome;
    private String underlyingDynamicPage;
    private String contentForwardSite;
    private String showMidColumn;
    private String showMenuColumn;
    private String showAdColumn;
    private String showHomeMenu;
    private String showHomeAd;
    private String showHomeMid;
    private String showTopMenu;
    private String midColumnWidth;
    private String useWysiwygContent;
    private String useWysiwygPost;
    
    private String backgroundImage;
    private String backgroundRepeat;
    private String backgroundAttach;
    private String backgroundColor;
    private String backgroundPosition;
    private String contentBgColor;
    
    private String absolutePosition;
    private String absoluteTop;
    private String absoluteLeft;

    private String functionalType;
    private String ecEnabled;
    private String frontDisplayFeed;
    
    private String siteIconUrl;

    public String getUnderlyingDynamicPage() {
        return underlyingDynamicPage;
    }

    public void setUnderlyingDynamicPage(String underlyingDynamicPage) {
        this.underlyingDynamicPage = underlyingDynamicPage;
    }

    public String getFunctionalType() {
        return functionalType;
    }

    public void setFunctionalType(String functionalType) {
        this.functionalType = functionalType;
    }

    public String getEcEnabled() {
        return ecEnabled;
    }

    public void setEcEnabled(String ecEnabled) {
        this.ecEnabled = ecEnabled;
    }

    public String getAbsolutePosition() {
        return absolutePosition;
    }

    public void setAbsolutePosition(String absolutePosition) {
        this.absolutePosition = absolutePosition;
    }

    public String getAbsoluteTop() {
        return absoluteTop;
    }

    public void setAbsoluteTop(String absoluteTop) {
        this.absoluteTop = absoluteTop;
    }

    public String getAbsoluteLeft() {
        return absoluteLeft;
    }

    public void setAbsoluteLeft(String absoluteLeft) {
        this.absoluteLeft = absoluteLeft;
    }

    public String getBackgroundImage() {
        return backgroundImage;
    }

    public void setBackgroundImage(String backgroundImage) {
        this.backgroundImage = backgroundImage;
    }

    public String getBackgroundRepeat() {
        return backgroundRepeat;
    }

    public void setBackgroundRepeat(String backgroundRepeat) {
        this.backgroundRepeat = backgroundRepeat;
    }

    public String getBackgroundAttach() {
        return backgroundAttach;
    }

    public void setBackgroundAttach(String backgroundAttch) {
        this.backgroundAttach = backgroundAttch;
    }

    public String getBackgroundColor() {
        return backgroundColor;
    }

    public void setBackgroundColor(String backgroundColor) {
        this.backgroundColor = backgroundColor;
    }

    public String getBackgroundPosition() {
        return backgroundPosition;
    }

    public void setBackgroundPosition(String backgroundPosition) {
        this.backgroundPosition = backgroundPosition;
    }

    public String getContentForwardSite() {
        return contentForwardSite;
    }

    public void setContentForwardSite(String contentForwardSite) {
        this.contentForwardSite = contentForwardSite;
    }

    public String getUnderlyingHome() {
        return underlyingHome;
    }

    public void setUnderlyingHome(String underlyingHome) {
        this.underlyingHome = underlyingHome;
    }

    public String getLayoutPage() {
        return layoutPage;
    }

    public void setLayoutPage(String layoutPage) {
        this.layoutPage = layoutPage;
    }

    public String getHeaderAd() {
        return headerAd;
    }

    public void setHeaderAd(String headerAd) {
        this.headerAd = headerAd;
    }

    public String getHeaderImageHeight() {
        return headerImageHeight;
    }

    public void setHeaderImageHeight(String headerImageHeight) {
        this.headerImageHeight = headerImageHeight;
    }

    public String getHeaderImageWidth() {
        return headerImageWidth;
    }

    public void setHeaderImageWidth(String headerImageWidth) {
        this.headerImageWidth = headerImageWidth;
    }

    public String getDisplayAllHome() {
        return displayAllHome;
    }

    public void setDisplayAllHome(String displayAllHome) {
        this.displayAllHome = displayAllHome;
    }

    public String getMenuFrontColor() {
        return menuFrontColor;
    }

    public void setMenuFrontColor(String menuFrontColor) {
        this.menuFrontColor = menuFrontColor;
    }

    public String getMenuBackColor() {
        return menuBackColor;
    }

    public void setMenuBackColor(String menuBackColor) {
        this.menuBackColor = menuBackColor;
    }

    public String getMenuLineColor() {
        return menuLineColor;
    }

    public void setMenuLineColor(String menuLineColor) {
        this.menuLineColor = menuLineColor;
    }

    public String getHeaderImage() {
        return headerImage;
    }

    public void setHeaderImage(String headerImage) {
        this.headerImage = headerImage;
    }

    public String getMenuWidth() {
        return menuWidth;
    }

    public void setMenuWidth(String menuWidth) {
        this.menuWidth = menuWidth;
    }

    public String getAdWidth() {
        return adWidth;
    }

    public void setAdWidth(String adWidth) {
        this.adWidth = adWidth;
    }

    public String getSiteGroup() {
        return siteGroup;
    }

    public String getSiteConfig() {
        return siteGroup;
    }

    public void setSiteGroup(String siteGroup) {
        this.siteGroup = siteGroup;
    }

    /** 
     * Method validate
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {
        // TODO Auto-generated method stub
        return null;
    }

    /** 
     * Method reset
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // TODO Auto-generated method stub
    }

    /** 
     * Returns the width.
     * @return Integer
     */
    public String getWidth() {
        return width;
    }

    /** 
     * Set the width.
     * @param width The width to set
     */
    public void setWidth(String width) {
        this.width = width;
    }

    /** 
     * Returns the track_google.
     * @return String
     */
    public String getTrack_google() {
        return track_google;
    }

    /** 
     * Set the track_google.
     * @param track_google The track_google to set
     */
    public void setTrack_google(String track_google) {
        this.track_google = track_google;
    }

    /** 
     * Returns the keywords.
     * @return String
     */
    public String getKeywords() {
        return keywords;
    }

    /** 
     * Set the keywords.
     * @param keywords The keywords to set
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    /** 
     * Returns the meta.
     * @return String
     */
    public String getMeta() {
        return meta;
    }

    /** 
     * Set the meta.
     * @param meta The meta to set
     */
    public void setMeta(String meta) {
        this.meta = meta;
    }

    public String getHeader() {
        return header;
    }

    public void setHeader(String header) {
        this.header = header;
    }

    public String getColCount() {
        return colCount;
    }

    public void setColCount(String colCount) {
        this.colCount = colCount;
    }

    public String getClrSubmenuBg() {
        return clrSubmenuBg;
    }

    public void setClrSubmenuBg(String clrSubmenuBg) {
        this.clrSubmenuBg = clrSubmenuBg;
    }

    public String getClrBorders() {
        return clrBorders;
    }

    public void setClrBorders(String clrBorders) {
        this.clrBorders = clrBorders;
    }

    public String getContactInfo() {
        return contactInfo;
    }

    public void setContactInfo(String contactInfo) {
        this.contactInfo = contactInfo;
    }

    public String getMenuReverse() {
        return menuReverse;
    }

    public void setMenuReverse(String menuReverse) {
        this.menuReverse = menuReverse;
    }

    public String getShowMidColumn() {
        return showMidColumn;
    }

    public void setShowMidColumn(String showMidColumn) {
        this.showMidColumn = showMidColumn;
    }

    public String getMidColumnWidth() {
        return midColumnWidth;
    }

    public void setMidColumnWidth(String midColumnWidth) {
        this.midColumnWidth = midColumnWidth;
    }

    public String getUseWysiwygContent() {
        return useWysiwygContent;
    }

    public void setUseWysiwygContent(String useWysiwygContent) {
        this.useWysiwygContent = useWysiwygContent;
    }

    public String getUseWysiwygPost() {
        return useWysiwygPost;
    }

    public void setUseWysiwygPost(String useWysiwygPost) {
        this.useWysiwygPost = useWysiwygPost;
    }

    public String getShowMenuColumn() {
        return showMenuColumn;
    }

    public void setShowMenuColumn(String showMenuColumn) {
        this.showMenuColumn = showMenuColumn;
    }

    public String getShowAdColumn() {
        return showAdColumn;
    }

    public void setShowAdColumn(String showAdColumn) {
        this.showAdColumn = showAdColumn;
    }

    public String getShowHomeMenu() {
        return showHomeMenu;
    }

    public void setShowHomeMenu(String showHomeMenu) {
        this.showHomeMenu = showHomeMenu;
    }

    public String getShowHomeAd() {
        return showHomeAd;
    }

    public void setShowHomeAd(String showHomeAd) {
        this.showHomeAd = showHomeAd;
    }

    public String getShowHomeMid() {
        return showHomeMid;
    }

    public void setShowHomeMid(String showHomeMid) {
        this.showHomeMid = showHomeMid;
    }

    public String getShowTopMenu() {
        return showTopMenu;
    }

    public void setShowTopMenu(String showTopMenu) {
        this.showTopMenu = showTopMenu;
    }

    public String getFrontDisplayFeed() {
        return frontDisplayFeed;
    }

    public void setFrontDisplayFeed(String frontDisplayFeed) {
        this.frontDisplayFeed = frontDisplayFeed;
    }

    public String getSiteIconUrl() {
        return siteIconUrl;
    }

    public void setSiteIconUrl(String siteIconUrl) {
        this.siteIconUrl = siteIconUrl;
    }

    public String getContentBgColor() {
        return contentBgColor;
    }

    public void setContentBgColor(String contentBgColor) {
        this.contentBgColor = contentBgColor;
    }
    
    
}
