/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.seox.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 11-22-2006
 * 
 * XDoclet definition:
 * @struts.form name="catmanageform"
 */
public class CatManageForm extends ActionForm {
    /*
     * Generated fields
     */

    /** subcmd property */
    private String subcmd;

    /** category property */
    private String category;

    /*
     * Generated Methods
     */

    /** 
     * Method validate
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {
        // TODO Auto-generated method stub
        return null;
    }

    /** 
     * Method reset
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // TODO Auto-generated method stub
    }

    /** 
     * Returns the subcmd.
     * @return String
     */
    public String getSubcmd() {
        return subcmd;
    }

    /** 
     * Set the subcmd.
     * @param subcmd The subcmd to set
     */
    public void setSubcmd(String subcmd) {
        this.subcmd = subcmd;
    }

    /** 
     * Returns the category.
     * @return String
     */
    public String getCategory() {
        return category;
    }

    /** 
     * Set the category.
     * @param category The category to set
     */
    public void setCategory(String category) {
        this.category = category;
    }
}
