/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.seox.struts;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.log4j.Logger;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.jtrend.struts.core.LoginRequiredJtrendAction;
import com.seox.db.Keyword;
import com.seox.struts.form.KeywordAddForm;
import com.seox.util.KeywordUtil;
import com.seox.work.UserBO;

/** 
 * MyEclipse Struts
 * Creation date: 10-29-2006
 * 
 * XDoclet definition:
 * @struts.action path="/keyword_add_form_submit" name="keywordaddform" input="/jsp/login_statics/keywords.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/jsp/layout/layout.jsp"
 */
public class KeywordAddFormAction extends LoginRequiredJtrendAction {
    /*
     * Generated Methods
     */

    /** 
     * Method execute
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    
    private static Logger m_logger = Logger.getLogger(KeywordAddFormAction.class);
    
    public ActionForward ex(ActionMapping mapping, ActionForm form, HttpServletRequest request,
            HttpServletResponse response) {

        KeywordAddForm keywordaddform = (KeywordAddForm) form;// TODO Auto-generated method stub
        HttpSession session = request.getSession();
        
        if (!isMissing(keywordaddform.getKeyword())) {
            
            System.out.println("### Keyword added ### " + keywordaddform.getKeyword());
            
            String kw = keywordaddform.getKeyword().trim();
            kw = KeywordUtil.normalizeKeyword(kw);
            
            UserBO userBO = getUserBO(session);

            Keyword keyword = new Keyword();
            keyword.setEnteredT(new Date());
            keyword.setKeyword(kw);
            keyword.setLastDayNum(0);
            keyword.setLastWeekNum(0);

            if (userBO.addKeyword(keyword) ) {
                session.removeAttribute("kv_domains");
                session.removeAttribute("kv_keywords");
                session.setAttribute("k_top_text", "Keyword " + kw + " was successfully added");
            } else {
                session.setAttribute("k_top_text", "Internal error occurred. Category " + kw + " was not added. Please try again");
            }
        }

        keywordaddform.setKeyword(null);
        setPage(session, "keywords", true);
        return mapping.findForward("success");    
    }
}
