/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.seox.struts;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.log4j.Logger;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.jtrend.struts.core.JtrendAction;
import com.jtrend.struts.core.LoginRequiredJtrendAction;
import com.seox.db.Keyword;
import com.seox.db.UserDomain;
import com.seox.struts.form.KeywordForm;
import com.seox.work.UserBO;
import com.seox.work.UserBOPool;

/** 
 * MyEclipse Struts
 * Creation date: 11-15-2006
 * 
 * XDoclet definition:
 * @struts.action path="/keyword_form_submit" name="keywordform" scope="request" validate="true"
 * @struts.action-forward name="success" path="/jsp/layout/layout.jsp" contextRelative="true"
 */
public class KeywordFormAction extends LoginRequiredJtrendAction {
    /*
     * Generated Methods
     */

    /** 
     * Method execute
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward ex(ActionMapping mapping, ActionForm form, HttpServletRequest request,
            HttpServletResponse response) {

        KeywordForm keywordform = (KeywordForm) form;// TODO Auto-generated method stub
        HttpSession session = request.getSession();

        UserBO userBO = getUserBO(session);
        
        if (isMissing(keywordform.getCmd())) {
            
        } else {
            if (keywordform.getCmd().equalsIgnoreCase("add")) {
                if (!isMissing(keywordform.getKeyword())) {
                    
                    m_logger.debug("Adding keyword " + keywordform.getKeyword());
                }
            } else if (keywordform.getCmd().equalsIgnoreCase("delete")) {
                if (!isMissing(keywordform.getKeyword())) {
                    
                    m_logger.debug("Deleting (Deactivating) Keyword " + keywordform.getKeyword());
                    
                    long keywordId = Long.parseLong(keywordform.getKeyword());
                    Keyword keyword = userBO.findKeywordById(new Long(keywordId));
                    if (keyword != null) {
                        session.removeAttribute("kv_domains");
                        session.removeAttribute("kv_keywords");
                        userBO.deleteKeywordFromUser(keyword);
                    } else {
                        m_logger.debug("Keyword not found by id " + keywordId + "");
                    }
                }
            }
        }
        
        setPage(session, "keywords", true);
        return mapping.findForward("success");    
    }
    private static Logger m_logger = Logger.getLogger(KeywordFormAction.class);
}
